### ISSUE TITLE
getting_started/data_upload.md 에서 SSH 키에 대한 설명이 이상합니다

### ISSUE THREAD

**Issue by ywkoATsmartmind** [smartmind-team/thanosql-docs#172]
API 키 설명인지 SSH(SFTP) 키 설명인지 혼란스럽습니다.

예를 들어, SSH 키를 재 발급하는 기능은 없는데 있는 것 처럼 설명하고 있습니다.

SSH 키의 경우 클립보드로 복사하지 않고 파일을 다운로드 하는 방식인데 설명은 클립보드로 복사되는 것 처럼 되어 있습니다. 빈 파일을 만들고 거기에 복사한 것을 붙여넣는 것이 아니라 다운로드 받은 파일을 적당한 폴더로 옮기는 것으로 설명하는 것이 좋겠습니다.

**Comment by inwookie** [comment]
@yeemh  

웹팀이랑 연계해서 필요한 이미지 받아서 고쳐주세요!
