### ISSUE TITLE
getting_started/data_upload.md 에서 sftp 커맨드 설명 수정 

### ISSUE THREAD

**Issue by ywkoATsmartmind** [smartmind-team/thanosql-docs#173]
sftp -i [the absolute path of the pem file] [name of workspace]@engine.thanosql.ai

pem 파일을 굳이 absolute path 로 줄 필요 없습니다. 예를 들어, 현재 폴더에 있다면

sftp -i ./key.pem ... 

이렇게 해도 잘 동작합니다. 따라서, path of the pem file 로 수정하는 것이 좋겠습니다.

**Comment by inwookie** [comment]
https://github.com/smartmind-team/thanosql-docs/pull/174 에서 수정 하고 [docs](https://docs.thanosql.ai/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_file/#file-delete)에 반영 했습니다.
